FROM ubuntu:18.04
ENV DEBIAN_FRONTEND noninteractive
# Install
RUN \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential clang && \
  apt-get install -y software-properties-common && \
  apt-get install -y byobu curl git htop man unzip vim wget zsh libomp-dev gcc g++ libssl-dev ninja-build
RUN \
  apt-get install -y subversion cmake qt5-default && \
  rm -rf /var/lib/apt/lists/*

RUN curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Add files
# ADD root/.bashrc /root/.bashrc

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /work

# Define default command.
CMD ["zsh"]

# Update gcc/g++ to v4.9
# RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test
# RUN apt-get update -qq
# RUN apt-get install -qq gcc g++
# RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc 90
# RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++ 90
# RUN update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov 90

# Install LCOV
# RUN git clone https://github.com/linux-test-project/lcov.git
# RUN make -C lcov install
# RUN apt-get install -y ruby
# RUN gem install coveralls-lcov

# Update CMake to v3.3.2
RUN wget https://github.com/Kitware/CMake/releases/download/v3.17.1/cmake-3.17.1.tar.gz -O - | tar zxvf -
RUN cd cmake-3.17.1 && ./bootstrap && make && make install

# OpenMesh install
# ref

RUN git clone https://github.com/gig2/OpenMesh openmesh && \
mkdir build-openmesh && \
cd build-openmesh && \
cmake ../openmesh -DBUILD_APPS=OFF -GNinja && \
ninja && \
ninja install && \
cd .. 

# Show environments
RUN echo "--- Build Enviroment ---"
RUN cat /etc/lsb-release
RUN gcc --version | grep gcc
RUN g++ --version | grep g++
RUN clang --version | grep version
RUN clang++ --version | grep version
RUN cmake --version | grep version
RUN echo "------------------------"